package my.chat.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("album", "id", Album.class);
		arp.addMapping("singers", "id", Singers.class);
		arp.addMapping("songs", "id", Songs.class);
		arp.addMapping("type", "id", Type.class);
		arp.addMapping("user", "id", User.class);
	}
}

