package my.chat.model

import com.jfinal.plugin.activerecord.ActiveRecordPlugin

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 * ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 * _MappingKit.mapping(arp);
 * me.add(arp);
 * }
</pre> *
 */
object _MappingKit {

    fun mapping(arp: ActiveRecordPlugin) {
        arp.addMapping("album", "id", Album::class.java)
        arp.addMapping("singers", "id", Singers::class.java)
        arp.addMapping("songs", "id", Songs::class.java)
        arp.addMapping("type", "id", Type::class.java)
        arp.addMapping("user", "id", User::class.java)
    }
}

