package my.chat.model

import my.chat.model.base.BaseArticleComment

/**
 * Generated by JFinal.
 */
class ArticleComment : BaseArticleComment<ArticleComment>() {
    companion object {
        val dao = ArticleComment().dao()
    }
}
