package my.chat.model;

import my.chat.model.base.BaseSingers;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Singers extends BaseSingers<Singers> {
	public static final Singers dao = new Singers().dao();
}
