package my.chat.model;

import my.chat.model.base.BaseSongs;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Songs extends BaseSongs<Songs> {
	public static final Songs dao = new Songs().dao();
}
