package my.chat.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseAlbum<M extends BaseAlbum<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setSingerid(java.lang.Integer singerid) {
		set("singerid", singerid);
		return (M)this;
	}

	public java.lang.Integer getSingerid() {
		return get("singerid");
	}

	public M setAlbumname(java.lang.String albumname) {
		set("albumname", albumname);
		return (M)this;
	}

	public java.lang.String getAlbumname() {
		return get("albumname");
	}

	public M setAlbumurl(java.lang.String albumurl) {
		set("albumurl", albumurl);
		return (M)this;
	}

	public java.lang.String getAlbumurl() {
		return get("albumurl");
	}

	public M setAlbumdate(java.lang.String albumdate) {
		set("albumdate", albumdate);
		return (M)this;
	}

	public java.lang.String getAlbumdate() {
		return get("albumdate");
	}

	public M setAlbumpic(java.lang.String albumpic) {
		set("albumpic", albumpic);
		return (M)this;
	}

	public java.lang.String getAlbumpic() {
		return get("albumpic");
	}

}
