package my.chat.model.base

import com.jfinal.plugin.activerecord.IBean
import com.jfinal.plugin.activerecord.Model

/**
 * Generated by JFinal, do not modify this file.
 */
abstract class BaseType<M : BaseType<M>> : Model<M>(), IBean {

    fun setId(id: Int?): M {
        set("id", id)
        return this as M
    }

    val id: Int?
        get() = get<Int>("id")

    fun setName(name: String?): M {
        set("name", name)
        return this as M
    }

    val name: String?
        get() = get("name")

    fun setParentid(parentid: Int?): M {
        set("parentid", parentid)
        return this as M
    }

    val parentid: Int?
        get() = get<Int>("parentid")

}
