package my.chat.model.base

import com.jfinal.plugin.activerecord.IBean
import com.jfinal.plugin.activerecord.Model

/**
 * Generated by JFinal, do not modify this file.
 */
abstract class BaseSongs<M : BaseSongs<M>> : Model<M>(), IBean {

    fun setId(id: Int?): M {
        set("id", id)
        return this as M
    }

    val id: Int?
        get() = get<Int>("id")

    fun setAlbumid(albumid: Int?): M {
        set("albumid", albumid)
        return this as M
    }

    val albumid: Int?
        get() = get<Int>("albumid")

    fun setName(name: String?): M {
        set("name", name)
        return this as M
    }

    val name: String?
        get() = get("name")

    fun setUrl(url: String?): M {
        set("url", url)
        return this as M
    }

    val url: String?
        get() = get("url")

    fun setMvurl(mvurl: String?): M {
        set("mvurl", mvurl)
        return this as M
    }

    val mvurl: String?
        get() = get("mvurl")

    fun setAlias(alias: String?): M {
        set("alias", alias)
        return this as M
    }

    val alias: String?
        get() = get("alias")

    fun setDuration(duration: Int?): M {
        set("duration", duration)
        return this as M
    }

    val duration: Int?
        get() = get<Int>("duration")

}
