package my.chat.model.base

import com.jfinal.plugin.activerecord.IBean
import com.jfinal.plugin.activerecord.Model
import java.util.*

/**
 * Generated by JFinal, do not modify this file.
 */
abstract class BaseTweets<M : BaseTweets<M>> : Model<M>(), IBean {

    fun setId(id: Int?): M {
        set("id", id)
        return this as M
    }

    val id: Int?
        get() = get<Int>("id")

    fun setUid(uid: Int?): M {
        set("uid", uid)
        return this as M
    }

    val uid: Int?
        get() = get<Int>("uid")

    fun setUname(uname: String?): M {
        set("uname", uname)
        return this as M
    }

    val uname: String?
        get() = get("uname")

    fun setContent(content: String?): M {
        set("content", content)
        return this as M
    }

    val content: String?
        get() = get("content")

    fun setComments(comments: Int?): M {
        set("comments", comments)
        return this as M
    }

    val comments: Int?
        get() = get<Int>("comments")

    fun setTime(time: Date): M {
        set("time", time)
        return this as M
    }

    val time: Date
        get() = get("time")
}
