package my.chat.model.base

import com.jfinal.plugin.activerecord.IBean
import com.jfinal.plugin.activerecord.Model

/**
 * Generated by JFinal, do not modify this file.
 */
abstract class BaseArticleComment<M : BaseArticleComment<M>> : Model<M>(), IBean {

    fun setId(id: Int?): M {
        set("id", id)
        return this as M
    }

    val id: Int?
        get() = get<Int>("id")

    fun setAid(aid: Int?): M {
        set("aid", aid)
        return this as M
    }

    val aid: Int?
        get() = get<Int>("aid")

    fun setUid(uid: Int?): M {
        set("uid", uid)
        return this as M
    }

    val uid: Int?
        get() = get<Int>("uid")

    fun setContent(content: String): M {
        set("content", content)
        return this as M
    }

    val content: String
        get() = get("content")

    fun setTime(time: java.util.Date): M {
        set("time", time)
        return this as M
    }

    val time: java.util.Date
        get() = get("time")

}
