package my.chat.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSingers<M extends BaseSingers<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}

	public java.lang.String getName() {
		return get("name");
	}

	public M setMusic(java.lang.String music) {
		set("music", music);
		return (M)this;
	}

	public java.lang.String getMusic() {
		return get("music");
	}

	public M setHomepage(java.lang.String homepage) {
		set("homepage", homepage);
		return (M)this;
	}

	public java.lang.String getHomepage() {
		return get("homepage");
	}

	public M setType(java.lang.Integer type) {
		set("type", type);
		return (M)this;
	}

	public java.lang.Integer getType() {
		return get("type");
	}

	public M setInitials(java.lang.String initials) {
		set("initials", initials);
		return (M)this;
	}

	public java.lang.String getInitials() {
		return get("initials");
	}

	public M setSingerid(java.lang.Integer singerid) {
		set("singerid", singerid);
		return (M)this;
	}

	public java.lang.Integer getSingerid() {
		return get("singerid");
	}

}
