package my.chat.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setUsername(java.lang.String username) {
		set("username", username);
		return (M)this;
	}

	public java.lang.String getUsername() {
		return get("username");
	}

	public M setPassword(java.lang.String password) {
		set("password", password);
		return (M)this;
	}

	public java.lang.String getPassword() {
		return get("password");
	}

	public M setEmail(java.lang.String email) {
		set("email", email);
		return (M)this;
	}

	public java.lang.String getEmail() {
		return get("email");
	}

	public M setPhone(java.lang.String phone) {
		set("phone", phone);
		return (M)this;
	}

	public java.lang.String getPhone() {
		return get("phone");
	}

	public M setIdCard(java.lang.String idCard) {
		set("idCard", idCard);
		return (M)this;
	}

	public java.lang.String getIdCard() {
		return get("idCard");
	}

	public M setNickname(java.lang.String nickname) {
		set("nickname", nickname);
		return (M)this;
	}

	public java.lang.String getNickname() {
		return get("nickname");
	}

	public M setBorndate(java.util.Date borndate) {
		set("borndate", borndate);
		return (M)this;
	}

	public java.util.Date getBorndate() {
		return get("borndate");
	}

	public M setGender(java.lang.Integer gender) {
		set("gender", gender);
		return (M)this;
	}

	public java.lang.Integer getGender() {
		return get("gender");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public M setSessionStr(java.lang.String sessionStr) {
		set("sessionStr", sessionStr);
		return (M)this;
	}

	public java.lang.String getSessionStr() {
		return get("sessionStr");
	}

	public M setCountry(java.lang.String country) {
		set("country", country);
		return (M)this;
	}

	public java.lang.String getCountry() {
		return get("country");
	}

	public M setProvince(java.lang.String province) {
		set("province", province);
		return (M)this;
	}

	public java.lang.String getProvince() {
		return get("province");
	}

	public M setCity(java.lang.String city) {
		set("city", city);
		return (M)this;
	}

	public java.lang.String getCity() {
		return get("city");
	}

	public M setDistrict(java.lang.String district) {
		set("district", district);
		return (M)this;
	}

	public java.lang.String getDistrict() {
		return get("district");
	}

	public M setAddressDetails(java.lang.String addressDetails) {
		set("addressDetails", addressDetails);
		return (M)this;
	}

	public java.lang.String getAddressDetails() {
		return get("addressDetails");
	}

	public M setPicSummary(java.lang.String picSummary) {
		set("picSummary", picSummary);
		return (M)this;
	}

	public java.lang.String getPicSummary() {
		return get("picSummary");
	}

	public M setDescription(java.lang.String description) {
		set("description", description);
		return (M)this;
	}

	public java.lang.String getDescription() {
		return get("description");
	}

	public M setRegisterTime(java.util.Date registerTime) {
		set("registerTime", registerTime);
		return (M)this;
	}

	public java.util.Date getRegisterTime() {
		return get("registerTime");
	}

	public M setActivateTime(java.util.Date activateTime) {
		set("activateTime", activateTime);
		return (M)this;
	}

	public java.util.Date getActivateTime() {
		return get("activateTime");
	}

	public M setLastLoginTime(java.util.Date lastLoginTime) {
		set("lastLoginTime", lastLoginTime);
		return (M)this;
	}

	public java.util.Date getLastLoginTime() {
		return get("lastLoginTime");
	}

}
